jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Upgrade pip
          command: /home/circleci/.pyenv/versions/3.10.1/bin/python3.10 -m pip install --upgrade pip
      - run: 
          name: Insall Dependices
          command: pip3 install requests lxml
      - run: 
          name: Begin
          command: python3 sign.py
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 0,1,2,3,7,8,23 * * *"
          filters:
            branches:
              only: 
                - main
    jobs:
      - build
